---
- name: Configure interfaces.
  hosts: switches
  gather_facts: false

  tasks:

    - name: Configure interfaces.
      cisco.ios.ios_interfaces:
        config:
          - name: Gigabitethernet 1/0/1
            description: fette
          - name: Gigabitethernet 1/0/2
            description: bra
          - name: Gigabitethernet 1/0/3
            description: med
          - name: Gigabitethernet 1/0/4
            description: bonus
        state: overridden
