---
# tasks file for interfaces

- name: Configure interfaces.
  cisco.ios.ios_interfaces:
    config: "{{ lookup('ansible.builtin.template', 'interface_template.j2') | ansible.builtin.from_yaml }}"
    state: "{{ interfaces_state }}"
  notify: Save ios.
