---
# tasks file for vlans

- name: Configure vlans.
  cisco.ios.ios_vlans:
    config: "{{ lookup('ansible.builtin.template', 'interface_template.j2') | ansible.builtin.from_yaml }}"
    state: "{{ vlans_state }}"
  notify: Save ios.
